try:
    raise Exception("hello")
except Exception as e:
    print(e)